eGov POC Cashiering System/Models/EmployeesViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace eGov_POC_Cashiering_System.Models
{
    [Table("Privileges")]
    public class Privilege
    {
        [Key]
        public string Name { get; set; }
        public string Group { get; set; }
        public Privilege()
        {

        }
    }

    [Table("RolePrivileges")]
    public class RolePrivilege
    {
        [Key, Column(Order = 0)]
        public string RoleID { get; set; }

        [Key, Column(Order = 1)]
        public string Name { get; set; }

        public RolePrivilege()
        {
            RoleID = "";
        }
    }

    [Table("AspNetRoles")]
    public class Role
    {
        [Key]
        [Column("Id")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string ID { get; set; }
        public string Name { get; set; }
        public int Level { get; set; }
        [ForeignKey("RoleID")]
        public virtual List<RolePrivilege> Privileges { get; set; }

        public Role()
        {
            Name = "";
        }
    }

    [Table("AspNetUserRoles")]
    public class EmployeeRole
    {
        [Key, Column("UserId", Order = 0)]
        public string UserID { get; set; }

        [Key, Column("RoleId", Order = 1)]
        public string ID { get; set; }

        public EmployeeRole()
        {
            UserID = "";
        }
    }

    [Table("AspNetUsers")]
    public class Employee
    {
        [Key]
        [Column("Id")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string ID { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        [ForeignKey("UserID")]
        public virtual List<EmployeeRole> Roles { get; set; }
        public string Location { get; set; }

        public Employee()
        {
            ID = "";
            UserName = "";
            Name = "";
            PhoneNumber = "";
            Roles = new List<EmployeeRole>();
            Location = "";
        }
    }

    public class EmployeesViewModel
    {
        //private readonly DBContext db = new DBContext();
        public List<Location> Locations { get; set; }
        public List<Employee> Employees { get; set; }
        public List<Role> EmployeeRoleProperties { get; set; }
        public RegisterViewModel RegisterModel { get; set; }
        public EmployeesViewModel()
        {
            RegisterModel = new RegisterViewModel();
            Locations = new List<Location>();
            EmployeeRoleProperties = new List<Role>();
            Employees = new List<Employee>();
        }

    }
}

eGov POC Cashiering System/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using eGov_POC_Cashiering_System.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using PostgreSQL.AspNet.Identity.EntityFramework;

namespace eGov_POC_Cashiering_System.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly DBContext db = new DBContext();

        [Authorize]
        public ActionResult Index()
        {
            EmployeesViewModel obj;
            if (Session["EmployeesViewModel"] == null)
            {
                obj = new EmployeesViewModel();
                Session["EmployeesViewModel"] = obj;
            }
            else
            {
                obj = Session["EmployeesViewModel"] as EmployeesViewModel;
            }
            obj.Employees = db.Employees.ToList();
            obj.EmployeeRoleProperties = db.EmployeeRoleProperties.ToList();
            obj.Locations = db.Locations.ToList();
            return View(obj);
        }

        [Authorize]
        public ActionResult AddEmployee()
        {
            EmployeesViewModel obj;
            if (Session["EmployeesViewModel"] == null)
            {
                obj = new EmployeesViewModel();
                Session["EmployeesViewModel"] = obj;
            }
            else
            {
                obj = Session["EmployeesViewModel"] as EmployeesViewModel;
            }
            obj.EmployeeRoleProperties = db.EmployeeRoleProperties.ToList();
            obj.Employees = db.Employees.ToList();
            obj.Locations = db.Locations.ToList();
            return View("AddEmployee", obj);
        }

        [Authorize]
        public ActionResult EditEmployee()
        {
            Employee Employee = db.Employees.Find(Request.Form["ID"]);
            return RedirectToAction("Index", new { editing = Employee.ID });
        }

        [Authorize]
        public ActionResult SaveEmployee()
        {
            Employee Employee = db.Employees.Find(Request.Form["ID"]);
            Employee.Name = Request.Form["Name"];
            Employee.UserName = Request.Form["UserName"];
            Employee.Email = Request.Form["Email"];
            Employee.Location = Request.Form["Location"];
            if (Request.Form["Roles"] != null)
            {
                List<string> roles = Request.Form["Roles"].Split(',').ToList();
                db.EmployeeRoles.ToList().ForEach(
                    x => {
                        if (x.UserID == Employee.ID)
                        {
                            db.EmployeeRoles.Remove(x);
                        }
                    }
                );
                roles.ForEach(
                    x => db.EmployeeRoles.Add(new EmployeeRole { UserID = Employee.ID, ID = x })
                );
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public ActionResult RemoveEmployee()
        {
            Employee Employee = db.Employees.Find(Request.Form["ID"]);
            db.Employees.Remove(Employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

eGov POC Cashiering System/Views/Employees/AddEmployee.cshtml
@using eGov_POC_Cashiering_System.Models
@using eGov_POC_Cashiering_System.App_Code

@{
    ViewBag.Title = "Add Employee";
}

@model EmployeesViewModel

@using (Html.BeginForm("Register", "Account", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Add a new employee.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.RegisterModel.Name, new { @class = "col-md-2 control-label" })
        <div class="col-md-4">
            <input type="text" autocomplete="off" name="Name" class="form-control">
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.RegisterModel.UserName, new { @class = "col-md-2 control-label" })
        <div class="col-md-4">
            <input type="text" autocomplete="off" name="UserName" class="form-control">
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.RegisterModel.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-4">
            <input type="text" autocomplete="off" name="Email" class="form-control">
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.RegisterModel.Roles, new { @class = "col-md-2 control-label" })
        <div class="col-md-4">
            <select name="Roles" multiple="multiple">
                @foreach (Role Role in Model.EmployeeRoleProperties)
                {
                    if (Utilities.HigherThanUserRole(User, Role) || User.IsInRole("Administrator"))
                    {
                        <option value="@Role.ID">@Role.Name</option>
                    }
                }
            </select>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.RegisterModel.Location, new { @class = "col-md-2 control-label" })
        <div class="col-md-4">
            <select name="Location" class="form-control">
                @foreach (Location Location in Model.Locations)
                {
                    <option value="@Location.ID">@Location.Name</option>
                }
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-4">
            <input type="submit" class="btn btn-default" value="Complete" />
        </div>
    </div>
}

<script type="text/javascript">
    window.addEventListener("load", function (event) {
        $(document.getElementsByName("Roles")[0]).multiselect();
    }, false);
</script>

eGov POC Cashiering System/Views/Employees/Index.cshtml
@using Microsoft.AspNet.Identity;
@using eGov_POC_Cashiering_System.Models
@using eGov_POC_Cashiering_System.App_Code
@{
    ViewBag.Title = "Employee";
}
@model EmployeesViewModel

@{
    int count = Model.Employees.Aggregate(0, (acc, Employee) => acc + 1);
}

<div class="row padding-bottom-md" style="float: right">
    @if (Utilities.HasPrivilege(User, "AddEmployee"))
    {
        <div class="col-sm-sm-4">
            <div class="btn btn-md btn-success" onclick="location.href='@Url.Action("AddEmployee", "Employees")'">
                <span class="glyphicon glyphicon-plus">&nbsp;</span>Add
            </div>
        </div>
    }
</div>

<div class="row padding-bottom-md">
    <div class="col-sm-sm-12">
        <div class="div-table">
            <div>
                <div class="div-table-cell middle th col-sm-2">
                    Name
                </div>
                <div class="div-table-cell middle th col-sm-2">
                    User Name
                </div>
                <div class="div-table-cell middle th col-sm-2">
                    Email
                </div>
                <div class="div-table-cell middle th col-sm-2">
                    Roles
                </div>
                <div class="div-table-cell middle th col-sm-2">
                    Location
                </div>
                <div class="div-table-cell middle th col-sm-2">
                    Actions
                </div>
            </div>
            @if (Model.Employees != null && Model.Employees.Count() > 0)
            {
                foreach (Employee Employee in Model.Employees)
                {
                    if (Request.QueryString["editing"] == Employee.ID)
                    {
                        using (Html.BeginForm("SaveEmployee", "Employees", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            <div class="div-table-cell middle td col-sm-2">
                                <input type="text" autocomplete="off" name="Name" class="form-control" value="@Html.DisplayFor(modelEmployee => Employee.Name)">
                            </div>
                            <div class="div-table-cell middle td col-sm-2">
                                <input type="text" autocomplete="off" name="UserName" class="form-control" value="@Html.DisplayFor(modelEmployee => Employee.UserName)">
                            </div>
                            <div class="div-table-cell middle td col-sm-2">
                                <input type="text" autocomplete="off" name="Email" class="form-control" value="@Html.DisplayFor(modelEmployee => Employee.Email)">
                            </div>
                            <div class="div-table-cell middle td col-sm-2">
                                <select name="Roles" multiple="multiple">
                                    @foreach (Role Role in Model.EmployeeRoleProperties)
                                    {
                                        if (Utilities.HigherThanUserRole(User, Employee))
                                        {
                                            if (Employee.Roles.Find(x => x.ID == Role.ID) != null)
                                            {
                                                <option value="@Role.ID" selected>@Role.Name</option>
                                            }
                                            else
                                            {
                                                <option value="@Role.ID">@Role.Name</option>
                                            }
                                        }
                                    }
                                </select>
                            </div>
                            <div class="div-table-cell middle td col-sm-2">
                                <select name="Location" class="form-control">
                                    @foreach (Location Location in Model.Locations)
                                    {
                                        if (Employee.Location == Location.ID)
                                        {
                                            <option value="@Location.ID" selected>@Location.Name</option>
                                        }
                                        else
                                        {
                                            <option value="@Location.ID">@Location.Name</option>
                                        }
                                    }
                                </select>
                            </div>
                            <div class="div-table-cell middle td col-sm-2">
                                <input type="hidden" name="ID" value="@Html.DisplayFor(modelEmployee => Employee.ID)">
                                <div class="btn btn-sm btn-success pull-right" onclick="SubmitClosestForm(this);">
                                    Save
                                </div>
                            </div>
                        }
                    }
                    else
                    {
                        <div>
                            <div class="div-table-cell middle td col-sm-2">
                                @Html.DisplayFor(modelEmployee => Employee.Name)
                            </div>
                            <div class="div-table-cell middle td col-sm-2">
                                @Html.DisplayFor(modelEmployee => Employee.UserName)
                            </div>
                            <div class="div-table-cell middle td col-sm-2">
                                @Html.DisplayFor(modelEmployee => Employee.Email)
                            </div>
                            <div class="div-table-cell middle td col-sm-2">
                                @foreach (EmployeeRole Role in Employee.Roles)
                                {
                                    <span>@Model.EmployeeRoleProperties.Find(x => x.ID == Role.ID).Name</span><span>;</span>
                                }
                            </div>
                            <div class="div-table-cell middle td col-sm-2">
                                @Model.Locations.Find(x => x.ID == Employee.Location).Name
                            </div>
                            <div class="div-table-cell middle td col-sm-2">
                                @if (
                                    Utilities.HasPrivilege(User, "EditEmployee")
                                    &&
                                    (Utilities.HigherThanUserRole(User, Employee) || User.IsInRole("Administrator"))
                                    &&
                                    Employee.ID != User.Identity.GetUserId()
                                )
                                {
                                    using (Html.BeginForm("EditEmployee", "Employees", FormMethod.Post, new { @class = "pull-left" }))
                                    {
                                        <input type="hidden" name="ID" value="@Html.DisplayFor(modelEmployee => Employee.ID)">
                                        <div class="btn btn-sm btn-default" onclick="SubmitClosestForm(this);">
                                            Edit
                                        </div>
                                    }
                                }
                                &nbsp;
                                @if (
                                    Utilities.HasPrivilege(User, "RemoveEmployee")
                                    &&
                                    (Utilities.HigherThanUserRole(User, Employee) || User.IsInRole("Administrator"))
                                    &&
                                    Employee.ID != User.Identity.GetUserId()
                                )
                                {
                                    using (Html.BeginForm("RemoveEmployee", "Employees", FormMethod.Post, new { @class = "pull-right" }))
                                    {
                                        <input type="hidden" name="ID" value="@Html.DisplayFor(modelEmployee => Employee.ID)">
                                        <div class="btn btn-sm btn-danger" onclick="SubmitClosestForm(this);">
                                            Remove
                                        </div>
                                    }
                                }
                            </div>
                        </div>
                    }
                }
            }
            else
            {
                <div class="row">
                    <div class="col-sm-22">
                        <h4 class="text-center">Empty.</h4>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@if (Request.QueryString["editing"] != null)
{
    <script type="text/javascript">
        window.addEventListener("load", function (event) {
            $(document.getElementsByName("Roles")[0]).multiselect();
        }, false);
    </script>
}