eGov POC Cashiering System/Models/EODReportsViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace eGov_POC_Cashiering_System.Models
{
    public class EODReport
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string ID { get; set; }
        public double DateOpened { get; set; }
        public decimal OpenCash { get; set; }
        public double CloseDate { get; set; }
        public string ClosedBy { get; set; }
        public decimal InHand { get; set; }

        public EODReport()
        {
            ID = "";
            DateOpened = 0;
            OpenCash = 0;
            CloseDate = 0;
            ClosedBy = "";
            InHand = 0;
        }
    }

    public class EODReportsViewModel
    {
        private readonly DBContext db = new DBContext();
        public List<Employee> Employees { get; set; }
        public List<EODReport> EODReports { get; set; }
        public List<Transaction> Transactions { get; set; }

        public EODReportsViewModel()
        {
            EODReports = new List<EODReport>();
            Transactions = new List<Transaction>();
            Employees = db.Employees.ToList();
        }

    }
}

eGov POC Cashiering System/Controllers/EODReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using eGov_POC_Cashiering_System.Models;

namespace eGov_POC_Cashiering_System.Controllers
{
    public class EODReportsController : Controller
    {
        private readonly DBContext db = new DBContext();

        [Authorize]
        public ActionResult Index()
        {
            EODReportsViewModel obj;
            if (Session["EODReportsViewModel"] == null)
            {
                obj = new EODReportsViewModel();
                Session["EODReportsViewModel"] = obj;
            }
            else
            {
                obj = Session["EODReportsViewModel"] as EODReportsViewModel;
            }
            obj.EODReports = db.EODReports.ToList();
            return View(obj);
        }

        [Authorize]
        public ActionResult AddEODReport()
        {
            EODReport item = new EODReport
            {
                ClosedBy = User.Identity.GetUserId()
        };
            db.EODReports.Add(item);
            db.SaveChanges();
            return RedirectToAction("Index", new { editing = item.ID });
        }

        [Authorize]
        public ActionResult EditEODReport()
        {
            EODReport item = db.EODReports.Find(Request.Form["ID"]);
            return RedirectToAction("Index", new { editing = item.ID });
        }

        [Authorize]
        public ActionResult SaveEODReport()
        {
            EODReport item = db.EODReports.Find(Request.Form["ID"]);
            item.DateOpened = double.Parse(Request.Form["DateOpened"]);
            item.OpenCash = decimal.Parse(Request.Form["OpenCash"]);
            item.CloseDate = double.Parse(Request.Form["CloseDate"]);
            item.InHand = decimal.Parse(Request.Form["InHand"]);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public ActionResult RemoveEODReport()
        {
            EODReport item = db.EODReports.Find(Request.Form["ID"]);
            db.EODReports.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

eGov POC Cashiering System/Views/EODReports/Index.cshtml
@using eGov_POC_Cashiering_System.Models
@using eGov_POC_Cashiering_System.App_Code
@{
    ViewBag.Title = "EOD Reports";
}
@model EODReportsViewModel

<div class="row padding-bottom-md" style="float: right">
    <div class="col-sm-sm-4">
        @if (Utilities.HasPrivilege(User, "AddEODReport"))
        {
            <div class="btn btn-md btn-success" onclick="location.href='@Url.Action("AddEODReport", "EODReports")'">
                <span class="glyphicon glyphicon-plus">&nbsp;</span>Add
            </div>
        }
    </div>
</div>

<div class="row padding-bottom-md">
    <div class="col-sm-sm-12">
        <div class="div-table">
            <div>
                <div class="div-table-cell middle th col-sm-2">
                    Date Opened
                </div>
                <div class="div-table-cell middle th col-sm-1">
                    Open Cash
                </div>
                <div class="div-table-cell middle th col-sm-2">
                    Close Date
                </div>
                <div class="div-table-cell middle th col-sm-3">
                    Closed By
                </div>
                <div class="div-table-cell middle th col-sm-1">
                    In Hand
                </div>
                <div class="div-table-cell middle th col-sm-1">
                    Difference
                </div>
                <div class="div-table-cell middle th col-sm-2">
                    Actions
                </div>
            </div>
            @if (Model.EODReports != null && Model.EODReports.Count() > 0)
            {
                foreach (EODReport item in Model.EODReports)
                {
                    if (Request.QueryString["editing"] == item.ID)
                    {
                        using (Html.BeginForm("SaveEODReport", "EODReports", FormMethod.Post))
                        {
                            <div class="div-table-cell middle td col-sm-2">
                                <input type="datetime-local" autocomplete="off" name="DateOpened" class="form-control" value="@Html.DisplayFor(modelEODReport => item.DateOpened)">
                            </div>
                            <div class="div-table-cell middle td col-sm-1">
                                <input type="number" step=".01" autocomplete="off" name="OpenCash" class="form-control" value="@Html.DisplayFor(modelEODReport => item.OpenCash)">
                            </div>
                            <div class="div-table-cell middle td col-sm-2">
                                <input type="datetime-local" autocomplete="off" name="CloseDate" class="form-control" value="@Html.DisplayFor(modelEODReport => item.CloseDate)">
                            </div>
                            <div class="div-table-cell middle td col-sm-3">
                                @Model.Employees.Find(x => x.ID == item.ClosedBy).Name
                            </div>
                            <div class="div-table-cell middle td col-sm-1">
                                <input type="number" step=".01" autocomplete="off" name="InHand" class="form-control" value="@Html.DisplayFor(modelEODReport => item.InHand)">
                            </div>
                            <div class="div-table-cell middle td col-sm-1">
                                <input type="number" step=".01" autocomplete="off" name="InHand" class="form-control" value="@Html.DisplayFor(modelEODReport => item.InHand)">
                            </div>
                            <div class="div-table-cell middle td col-sm-2">
                                <input type="hidden" name="ID" value="@Html.DisplayFor(modelEODReport => item.ID)">
                                <div class="btn btn-sm btn-success pull-right" onclick="SubmitClosestForm(this);">
                                    Save
                                </div>
                            </div>
                        }
                    }
                    else
                    {
                        <div>
                            <div class="div-table-cell middle td col-sm-3">
                                @Html.DisplayFor(modelEODReport => item.DateOpened)
                            </div>
                            <div class="div-table-cell middle td col-sm-1">
                                $ @Html.DisplayFor(modelEODReport => item.OpenCash)
                            </div>
                            <div class="div-table-cell middle td col-sm-3">
                                @Html.DisplayFor(modelEODReport => item.CloseDate)
                            </div>
                            <div class="div-table-cell middle td col-sm-2">
                                @Model.Employees.Find(x => x.ID == item.ClosedBy).Name
                            </div>
                            <div class="div-table-cell middle td col-sm-1">
                                $ @Html.DisplayFor(modelEODReport => item.InHand)
                            </div>
                            <div class="div-table-cell middle td col-sm-1">
                                @Html.DisplayFor(modelEODReport => item.InHand)
                            </div>
                            <div class="div-table-cell middle td col-sm-2">
                                @if (Utilities.HasPrivilege(User, "EditEODReport"))
                                {
                                    using (Html.BeginForm("EditEODReport", "EODReports", FormMethod.Post, new { @class = "pull-left" }))
                                    {
                                        <input type="hidden" name="ID" value="@Html.DisplayFor(modelEODReport => item.ID)">
                                        <div class="btn btn-sm btn-default" onclick="SubmitClosestForm(this);">
                                            Edit
                                        </div>
                                    }
                                }
                                &nbsp;
                                @if (Utilities.HasPrivilege(User, "RemoveEODReport"))
                                {
                                    using (Html.BeginForm("RemoveEODReport", "EODReports", FormMethod.Post, new { @class = "pull-right" }))
                                    {
                                        <input type="hidden" name="ID" value="@Html.DisplayFor(modelEODReport => item.ID)">
                                        <div class="btn btn-sm btn-danger" onclick="SubmitClosestForm(this);">
                                            Remove
                                        </div>
                                    }
                                }
                            </div>
                        </div>
                    }
                }
            }
            else
            {
                <div class="row">
                    <div class="col-sm-12">
                        <h4 class="text-center">Empty.</h4>
                    </div>
                </div>
            }
        </div>
    </div>
</div>