eGov POC Cashiering System/Models/SettingsViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace eGov_POC_Cashiering_System.Models
{
    public class IndexViewModel
    {
        public bool HasPassword { get; set; }
        public IList<UserLoginInfo> Logins { get; set; }
        public string PhoneNumber { get; set; }
        public bool TwoFactor { get; set; }
        public bool BrowserRemembered { get; set; }
    }

    [Table("Locations")]
    public class Location
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string ID { get; set; }
        public string Name { get; set; }

        public Location()
        {
            Name = "";
        }
    }

    public class LocationsViewModel
    {
        //private readonly DBContext db = new DBContext();
        public List<Location> Locations { get; set; }
        public LocationsViewModel()
        {
            Locations = new List<Location>();
        }

    }

    public class RolesViewModel
    {
        //private readonly DBContext db = new DBContext();
        public List<Role> Roles { get; set; }
        public List<Privilege> Privileges { get; set; }
        public RolesViewModel()
        {
            Roles = new List<Role>();
            Privileges = new List<Privilege>();
        }
    }

    public class ManageLoginsViewModel
    {
        public IList<UserLoginInfo> CurrentLogins { get; set; }
        public IList<AuthenticationDescription> OtherLogins { get; set; }
    }

    public class FactorViewModel
    {
        public string Purpose { get; set; }
    }

    public class SetPasswordViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class AddPhoneNumberViewModel
    {
        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string Number { get; set; }
    }

    public class VerifyPhoneNumberViewModel
    {
        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
    }

    public class ConfigureTwoFactorViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
    }
}

eGov POC Cashiering System/Controllers/SettingsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using eGov_POC_Cashiering_System.Models;
using System.Collections.Generic;

namespace eGov_POC_Cashiering_System.Controllers
{
    [Authorize]
    public class SettingsController : Controller
    {
        private readonly DBContext db = new DBContext();
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public SettingsController()
        {
        }

        public SettingsController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set 
            { 
                _signInManager = value; 
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        //
        // GET: /Manage/Index
        public async Task<ActionResult> Index(ManageMessageId? message)
        {
            ViewBag.StatusMessage =
                message == ManageMessageId.ChangePasswordSuccess ? "Your password has been changed."
                : message == ManageMessageId.SetPasswordSuccess ? "Your password has been set."
                : message == ManageMessageId.SetTwoFactorSuccess ? "Your two-factor authentication provider has been set."
                : message == ManageMessageId.Error ? "An error has occurred."
                : message == ManageMessageId.AddPhoneSuccess ? "Your phone number was added."
                : message == ManageMessageId.RemovePhoneSuccess ? "Your phone number was removed."
                : "";

            var userId = User.Identity.GetUserId();
            var model = new IndexViewModel
            {
                HasPassword = HasPassword(),
                PhoneNumber = await UserManager.GetPhoneNumberAsync(userId),
                TwoFactor = await UserManager.GetTwoFactorEnabledAsync(userId),
                Logins = await UserManager.GetLoginsAsync(userId),
                BrowserRemembered = await AuthenticationManager.TwoFactorBrowserRememberedAsync(userId)
            };
            return View(model);
        }

        [Authorize]
        public ActionResult Locations()
        {
            LocationsViewModel obj;
            if (Session["LocationsViewModel"] == null)
            {
                obj = new LocationsViewModel();
                Session["LocationsViewModel"] = obj;
            }
            else
            {
                obj = Session["LocationsViewModel"] as LocationsViewModel;
            }
            obj.Locations = db.Locations.ToList();
            return View(obj);
        }

        [Authorize]
        public ActionResult AddLocation()
        {
            Location location = new Location
            {
                Name = "Name here"
            };
            db.Locations.Add(location);
            db.SaveChanges();
            return RedirectToAction("Locations", new { editing = location.ID });
        }

        [Authorize]
        public ActionResult EditLocation()
        {
            Location Location = db.Locations.Find(Request.Form["ID"]);
            return RedirectToAction("Locations", new { editing = Location.ID });
        }

        [Authorize]
        public ActionResult SaveLocation()
        {
            Location Location = db.Locations.Find(Request.Form["ID"]);
            Location.Name = Request.Form["Name"];
            db.SaveChanges();
            return RedirectToAction("Locations");
        }

        [Authorize]
        [HttpPost]
        public ActionResult RemoveLocation()
        {
            Location Location = db.Locations.Find(Request.Form["ID"]);
            db.Locations.Remove(Location);
            db.SaveChanges();
            return RedirectToAction("Locations");
        }

        [Authorize]
        public ActionResult Roles()
        {
            RolesViewModel obj;
            if (Session["RolesViewModel"] == null)
            {
                obj = new RolesViewModel();
                Session["RolesViewModel"] = obj;
            }
            else
            {
                obj = Session["RolesViewModel"] as RolesViewModel;
            }
            obj.Roles = db.EmployeeRoleProperties.ToList();
            obj.Privileges = db.Privileges.ToList();
            return View(obj);
        }

        [Authorize]
        public ActionResult AddRole()
        {
            Role role = new Role
            {
                Level = 0
            };
            db.EmployeeRoleProperties.Add(role);
            db.SaveChanges();
            return RedirectToAction("Roles", new { editing = role.ID });
        }

        [Authorize]
        public ActionResult EditRole()
        {
            Role Role = db.EmployeeRoleProperties.Find(Request.Form["ID"]);
            return RedirectToAction("Roles", new { editing = Role.ID });
        }

        [Authorize]
        public ActionResult SaveRole()
        {
            Role Role = db.EmployeeRoleProperties.Find(Request.Form["ID"]);
            Role.Name = Request.Form["Name"];
            Role.Level = int.Parse(Request.Form["Level"]);
            if (Request.Form["Privileges"] != null)
            {
                List<string> privileges = Request.Form["Privileges"].Split(',').ToList();
                db.RolePrivileges.ToList().ForEach(
                    x => {
                        if (x.RoleID == Role.ID)
                        {
                            db.RolePrivileges.Remove(x);
                        }
                    }
                );
                privileges.ForEach(
                    x => db.RolePrivileges.Add(new RolePrivilege { RoleID = Role.ID, Name = x })
                );
            }
            db.SaveChanges();
            return RedirectToAction("Roles");
        }

        [Authorize]
        [HttpPost]
        public ActionResult RemoveRole()
        {
            Role Role = db.EmployeeRoleProperties.Find(Request.Form["ID"]);
            db.EmployeeRoleProperties.Remove(Role);
            db.SaveChanges();
            return RedirectToAction("Roles");
        }

        //
        // POST: /Manage/RemoveLogin
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RemoveLogin(string loginProvider, string providerKey)
        {
            ManageMessageId? message;
            var result = await UserManager.RemoveLoginAsync(User.Identity.GetUserId(), new UserLoginInfo(loginProvider, providerKey));
            if (result.Succeeded)
            {
                var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                if (user != null)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                }
                message = ManageMessageId.RemoveLoginSuccess;
            }
            else
            {
                message = ManageMessageId.Error;
            }
            return RedirectToAction("ManageLogins", new { Message = message });
        }

        //
        // GET: /Manage/AddPhoneNumber
        public ActionResult AddPhoneNumber()
        {
            return View();
        }

        //
        // POST: /Manage/AddPhoneNumber
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddPhoneNumber(AddPhoneNumberViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            // Generate the token and send it
            var code = await UserManager.GenerateChangePhoneNumberTokenAsync(User.Identity.GetUserId(), model.Number);
            if (UserManager.SmsService != null)
            {
                var message = new IdentityMessage
                {
                    Destination = model.Number,
                    Body = "Your security code is: " + code
                };
                await UserManager.SmsService.SendAsync(message);
            }
            return RedirectToAction("VerifyPhoneNumber", new { PhoneNumber = model.Number });
        }

        //
        // POST: /Manage/EnableTwoFactorAuthentication
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EnableTwoFactorAuthentication()
        {
            await UserManager.SetTwoFactorEnabledAsync(User.Identity.GetUserId(), true);
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (user != null)
            {
                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
            }
            return RedirectToAction("Index", "Manage");
        }

        //
        // POST: /Manage/DisableTwoFactorAuthentication
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DisableTwoFactorAuthentication()
        {
            await UserManager.SetTwoFactorEnabledAsync(User.Identity.GetUserId(), false);
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (user != null)
            {
                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
            }
            return RedirectToAction("Index", "Manage");
        }

        //

eGov POC Cashiering System/Views/Settings/AddPhoneNumber.cshtml
@model eGov_POC_Cashiering_System.Models.AddPhoneNumberViewModel
@{
    ViewBag.Title = "Phone Number";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("AddPhoneNumber", "Settings", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Add a phone number</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Number, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Number, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Submit" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

eGov POC Cashiering System/Views/Settings/ChangePassword.cshtml
@model eGov_POC_Cashiering_System.Models.ChangePasswordViewModel
@{
    ViewBag.Title = "Change Password";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("ChangePassword", "Settings", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Change Password Form</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.OldPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.OldPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.NewPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.NewPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Change password" class="btn btn-default" />
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

eGov POC Cashiering System/Views/Settings/Locations.cshtml
@using eGov_POC_Cashiering_System.Models
@{
    ViewBag.Title = "Location";
}
@model LocationsViewModel

<div class="row padding-bottom-md" style="float: right">
    <div class="col-sm-sm-4">
        <div class="btn btn-md btn-success" onclick="location.href='@Url.Action("AddLocation", "Settings")'">
            <span class="glyphicon glyphicon-plus">&nbsp;</span>Add
        </div>
    </div>
</div>

<div class="row padding-bottom-md">
    <div class="col-sm-12">
        <div class="div-table">
            <div>
                <div class="div-table-cell middle th col-sm-6">
                    Name
                </div>
                <div class="div-table-cell middle th col-sm-6">
                    Actions
                </div>
            </div>
            @if (Model.Locations != null && Model.Locations.Count() > 0)
            {
                foreach (Location Location in Model.Locations)
                {
                    if (Request.QueryString["editing"] == Location.ID)
                    {
                        using (Html.BeginForm("SaveLocation", "Settings", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            <div class="div-table-cell middle td col-sm-6">
                                <input type="text" autocomplete="off" name="Name" class="form-control" value="@Html.DisplayFor(modelLocation => Location.Name)">
                            </div>
                            <div class="div-table-cell middle td col-sm-6">
                                <input type="hidden" name="ID" value="@Html.DisplayFor(modelLocation => Location.ID)">
                                <div class="btn btn-sm btn-success pull-right" onclick="SubmitClosestForm(this);">
                                    Save
                                </div>
                            </div>
                        }
                    }
                    else
                    {
                        <div>
                            <div class="div-table-cell middle td col-sm-6">
                                @Html.DisplayFor(modelLocation => Location.Name)
                            </div>
                            <div class="div-table-cell middle td col-sm-6">
                                @using (Html.BeginForm("EditLocation", "Settings", FormMethod.Post, new { @class = "pull-left" }))
                                {
                                    <input type="hidden" name="ID" value="@Html.DisplayFor(modelLocation => Location.ID)">
                                    <div class="btn btn-sm btn-default" onclick="SubmitClosestForm(this);">
                                        Edit
                                    </div>
                                }
                                &nbsp;
                                @using (Html.BeginForm("RemoveLocation", "Settings", FormMethod.Post, new { @class = "pull-right" }))
                                {
                                    <input type="hidden" name="ID" value="@Html.DisplayFor(modelLocation => Location.ID)">
                                    <div class="btn btn-sm btn-danger" onclick="SubmitClosestForm(this);">
                                        Remove
                                    </div>
                                }
                            </div>
                        </div>
                    }
                }
            }
            else
            {
                <div class="row">
                    <div class="col-sm-6">
                        <h4 class="text-center">Empty.</h4>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

eGov POC Cashiering System/Views/Settings/ManageLogins.cshtml
@model eGov_POC_Cashiering_System.Models.ManageLoginsViewModel
@using Microsoft.Owin.Security
@{
    ViewBag.Title = "Manage your external logins";
}

<h2>@ViewBag.Title.</h2>

<p class="text-success">@ViewBag.StatusMessage</p>
@{
    var loginProviders = Context.GetOwinContext().Authentication.GetExternalAuthenticationTypes();
    if (loginProviders.Count() == 0) {
        <div>
            <p>
                There are no external authentication services configured. See <a href="https://go.microsoft.com/fwlink/?LinkId=313242">this article</a>
                for details on setting up this ASP.NET application to support logging in via external services.
            </p>
        </div>
    }
    else
    {
        if (Model.CurrentLogins.Count > 0)
        {
            <h4>Registered Logins</h4>
            <table class="table">
                <tbody>
                    @foreach (var account in Model.CurrentLogins)
                    {
                        <tr>
                            <td>@account.LoginProvider</td>
                            <td>
                                @if (ViewBag.ShowRemoveButton)
                                {
                                    using (Html.BeginForm("RemoveLogin", "Settings"))
                                    {
                                        @Html.AntiForgeryToken()
                                        <div>
                                            @Html.Hidden("loginProvider", account.LoginProvider)
                                            @Html.Hidden("providerKey", account.ProviderKey)
                                            <input type="submit" class="btn btn-default" value="Remove" title="Remove this @account.LoginProvider login from your account" />
                                        </div>
                                    }
                                }
                                else
                                {
                                    @: &nbsp;
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        if (Model.OtherLogins.Count > 0)
        {
            using (Html.BeginForm("LinkLogin", "Settings"))
            {
                @Html.AntiForgeryToken()
                <div id="socialLoginList">
                <p>
                    @foreach (AuthenticationDescription p in Model.OtherLogins)
                    {
                        <button type="submit" class="btn btn-default" id="@p.AuthenticationType" name="provider" value="@p.AuthenticationType" title="Log in using your @p.Caption account">@p.AuthenticationType</button>
                    }
                </p>
                </div>
            }
        }
    }
}

eGov POC Cashiering System/Views/Settings/Roles.cshtml
@using eGov_POC_Cashiering_System.Models
@{
    ViewBag.Title = "Roles";
}
@model RolesViewModel

<div class="row padding-bottom-md" style="float: right">
    <div class="col-sm-sm-4">
        <div class="btn btn-md btn-success" onclick="location.href='@Url.Action("AddRole", "Settings")'">
            <span class="glyphicon glyphicon-plus">&nbsp;</span>Add
        </div>
    </div>
</div>

<div class="row padding-bottom-md">
    <div class="col-sm-12">
        <div class="div-table">
            <div>
                <div class="div-table-cell middle th col-sm-3">
                    Name
                </div>
                <div class="div-table-cell middle th col-sm-3">
                    Level
                </div>
                <div class="div-table-cell middle th col-sm-3">
                    Privileges
                </div>
                <div class="div-table-cell middle th col-sm-3">
                    Actions
                </div>
            </div>
            @if (Model.Roles != null && Model.Roles.Count() > 0)
            {
                foreach (Role Role in Model.Roles)
                {
                    if (Request.QueryString["editing"] == Role.ID)
                    {
                        using (Html.BeginForm("SaveRole", "Settings", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            <div class="div-table-cell middle td col-sm-3">
                                <input type="text" autocomplete="off" name="Name" class="form-control" value="@Html.DisplayFor(modelRole => Role.Name)">
                            </div>
                            <div class="div-table-cell middle td col-sm-3">
                                <input type="number" autocomplete="off" name="Level" class="form-control" value="@Html.DisplayFor(modelRole => Role.Level)">
                            </div>
                            <div class="div-table-cell middle td col-sm-3">
                                <select name="Privileges" class="form-control" multiple>
                                    @foreach (Privilege Privilege in Model.Privileges)
                                    {
                                        if (Role.Privileges.Contains(new RolePrivilege { Name = Privilege.Name }))
                                        {
                                            <option value="@Privilege.Name" selected>@Privilege.Name (@Privilege.Group)</option>
                                        }
                                        else
                                        {
                                            <option value="@Privilege.Name">@Privilege.Name (@Privilege.Group)</option>
                                        }
                                    }
                                </select>
                            </div>
                            <div class="div-table-cell middle td col-sm-3">
                                <input type="hidden" name="ID" value="@Html.DisplayFor(modelRole => Role.ID)">
                                <div class="btn btn-sm btn-success pull-right" onclick="SubmitClosestForm(this);">
                                    Save
                                </div>
                            </div>
                        }
                    }
                    else
                    {
                        <div>
                            <div class="div-table-cell middle td col-sm-3">
                                @Html.DisplayFor(modelRole => Role.Name)
                            </div>
                            <div class="div-table-cell middle td col-sm-3">
                                @Html.DisplayFor(modelRole => Role.Level)
                            </div>
                            <div class="div-table-cell middle td col-sm-3">
                                @if (Role.Name == "Administrator")
                                {
                                    <span>All</span>
                                }
                                else
                                {
                                    foreach (RolePrivilege RolePrivilege in Role.Privileges)
                                    {
                                        Privilege Privilege = Model.Privileges.Find(x => x.Name == RolePrivilege.Name);
                                        <span>@Privilege.Name (@Privilege.Group)</span><span>;</span>
                                    }
                                }
                                </div>
                            <div class="div-table-cell middle td col-sm-3">
                                @if(Role.Name != "Administrator"){
                                    using (Html.BeginForm("EditRole", "Settings", FormMethod.Post, new { @class = "pull-left" }))
                                    {
                                        <input type="hidden" name="ID" value="@Html.DisplayFor(modelRole => Role.ID)">
                                        <div class="btn btn-sm btn-default" onclick="SubmitClosestForm(this);">
                                            Edit
                                        </div>
                                    }
                                    <span>&nbsp;</span>
                                    using (Html.BeginForm("RemoveRole", "Settings", FormMethod.Post, new { @class = "pull-right" }))
                                    {
                                        <input type="hidden" name="ID" value="@Html.DisplayFor(modelRole => Role.ID)">
                                        <div class="btn btn-sm btn-danger" onclick="SubmitClosestForm(this);">
                                            Remove
                                        </div>
                                    }
                                }
                            </div>
                        </div>
                    }
                }
            }
            else
            {
                <div class="row">
                    <div class="col-sm-6">
                        <h4 class="text-center">Empty.</h4>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<script type="text/javascript">
    window.addEventListener("load", function (event) {
        $(document.getElementsByName("Privileges")[0]).multiselect();
    }, false);
</script>

eGov POC Cashiering System/Views/Settings/SetPassword.cshtml
@model eGov_POC_Cashiering_System.Models.SetPasswordViewModel
@{
    ViewBag.Title = "Create Password";
}

<h2>@ViewBag.Title.</h2>
<p class="text-info">
    You do not have a local username/password for this site. Add a local
    account so you can log in without an external login.
</p>

@using (Html.BeginForm("SetPassword", "Settings", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <h4>Create Local Login</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.NewPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.NewPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Set password" class="btn btn-default" />
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

eGov POC Cashiering System/Views/Settings/VerifyPhoneNumber.cshtml
@model eGov_POC_Cashiering_System.Models.VerifyPhoneNumberViewModel
@{
    ViewBag.Title = "Verify Phone Number";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("VerifyPhoneNumber", "Settings", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("phoneNumber", @Model.PhoneNumber)
    <h4>Enter verification code</h4>
    <h5>@ViewBag.Status</h5>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Code, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Code, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Submit" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}